### ISSUE TITLE
[2.2] Replace Test T-shirt Simple Product with configurable product 

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#10]
Add 10 simple products with White/Black and all available sizes

**Comment by zhibek** [comment]
This is mostly working well now. We need to ensure the configurable product is the product listed on the catalogue category, so the user can access the configurable product details page to easily chose the colour/size of the product.

**Comment by zhibek** [comment]
To reiterate, we have two problems to fix before this issue can be considered complete:
- Configurable product must be the product shown on the catalogue listing pages (not the simple products).
- Configurable product must be shown as in stock (without needing to do anything manual in admin).

**Comment by babanesma** [comment]
configurable product is now showing in the listing but still out of stock
