### ISSUE TITLE
[2.3] Add behat script to test catalogue listing and pagination

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#14]

**Comment by babanesma** [comment]
behat is failing

**Comment by ahmedReda1** [comment]
merge #21 to solve the problem

**Comment by babanesma** [comment]
Pagination.feature is still failing even after merging #21 ( I didn't commit it )
this url is returning zero search results http://tee-shop.local/catalogsearch/result/?q=shirt
