### ISSUE TITLE
Module Splitting 

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#16]
@zhibek : We need to split this module (CamelCase_Tee ) out into different functional areas and I suggest dropping the CamelCase prefix and using TeeShop instead. I suggest the following modules: TeeShop_Core (for core config, like the package/theme setup and checkout config), TeeShop_Catalog (holding all the migrations we've done around categories and products), etc.

**Comment by babanesma** [comment]
assigning to @zhibek to check before merging with master

**Comment by zhibek** [comment]
Looks good to me. We may need to split the "TeeShop_Core" module if/when we have more functionality related to catalogue/checkout/etc. Closing for now.
