### ISSUE TITLE
[2.1] Create New Package/Theme

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#4]
Create new TeeShop theme folder structure and config (extending base rwd theme). Create config to activate new package/theme.

**Comment by babanesma** [comment]
Enable the new theme from config or migration 
Check this commit from training 
https://github.com/zhibek/tee-shop/commit/bbbb1e19f803a496877e45732fe729029c2ca8dd

**Comment by zhibek** [comment]
Looks good, but this migration can be moved to config (see #3 for example).

**Comment by zhibek** [comment]
Config example is in this commit: 32ac1188b8f5172d4dec7abd8e64181c645e9f2d

**Comment by ahmedReda1** [comment]
We moved bare theme migration to config.xml. Ready for review @zhibek.

**Comment by zhibek** [comment]
Looks good.
