### ISSUE TITLE
[2.1] Disable non-essential blocks

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#5]
Go through the layout configs and identify any non-essential blocks (the poll, functionality linking to the wishlist and any adverts are all non-essential). Add layout config to remove these non-essential blocks.

**Comment by babanesma** [comment]
Blocks removed : 
- Poll
- Paypal
- Sharing

Issue still under review to see if there are more blocks to remove

**Comment by zhibek** [comment]
Closing this ticket now. If we find other blocks that need to be removed later, an additional ticket can be opened.
