### ISSUE TITLE
[2.1] Test the Catalogue / Basket / Checkout

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#8]
Create a Behat script to select the "Test T-Shirt" product, add it to the basket and complete the checkout as a guest user. Verify relevant text on each page of the process so future failures can be linked back to a specific page in the process.

**Comment by babanesma** [comment]
Checkout step is still missing

**Comment by ahmedsamir89** [comment]
The checkout has been done and waiting for review

**Comment by zhibek** [comment]
This is functioning well, but we need to find a way to reduce the wait time between ajax steps in the checkout.

**Comment by ahmedReda1** [comment]
@zhibek  Now the waiting time is totally dependent on components creation

**Comment by zhibek** [comment]
@ahmedReda1 Please re-check this. Jenkins shows an error when it ran this build:
http://ci.zhibek.com/job/Tee-Shop/68/console

**Comment by zhibek** [comment]
@ahmedReda1 Latest CI build shows a success, with your changes!
http://ci.zhibek.com/job/Tee-Shop/72/console

Closing issue.
