### ISSUE TITLE
[2.2] Add new product attributes

### ISSUE THREAD

**Issue by babanesma** [zhibek/tee-shop#9]
- Brand
  - String 0-50 char 
  - Optional
- Fabric care
  - String 0-50 char
  - Optional
- Primary colour
  - List ( White, Black, Gray, Red, Blue, Green, Yellow, Purple, Brown )
- Size
  - List (XS, S, M, L, XL)

**Comment by babanesma** [comment]
change fabric-care to fabric_care 
change primary-colour to primary_colour 
Use helper data class to add these values as constants so you can refer to them anywhere else

**Comment by babanesma** [comment]
@ahmedReda1 
"Use helper data class to add these values as constants so you can refer to them anywhere else"
- helper data class is not created and constants are not referred

**Comment by zhibek** [comment]
@ahmedReda1 I can help you understand what's needed in the helper class - let me (or Adham) know when you start this and I'll assist.

**Comment by ahmedReda1** [comment]
hi @zhibek @babanesma 
i created a helper class to help us calling methods we use during migrations 
i added function  "getAttributeOptionValue" that we used in migration 0.1.6.0~0.1.7.0
and it worked just fine

**Comment by zhibek** [comment]
@ahmedReda1 Please check the code review.

**Comment by zhibek** [comment]
@ahmedReda1 That's good - almost there. Please see my latest code review for a few small changes.

**Comment by babanesma** [comment]
using of constants in all migrations is implemented in branch issue-16-module-splitting
